spring:
  profiles.active: local
  application.name: materiais-alternativos

liquibase:
  change-log: classpath:/db/db.master.xml
---
spring:
  profiles: local
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: localhost
    password: localhost
  jpa:
    database: oracle
    show-sql: true
liquibase:
  enabled: true
  drop-first: false
---
spring:
  profiles: dev
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@dev.test.com:1521:dev
    username: dev
    password: dev
  jpa:
    database: oracle
    show-sql: true
liquibase:
  enabled: true
  drop-first: false
---
spring:
  profiles: integration-test
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@integration.test.com:1521:dev
    username: integration
    password: integration
  jpa:
    database: oracle
    show-sql: false
liquibase:
  enabled: true
  drop-first: true
  contexts: tests
---
spring:
  profiles: prod
  datasource:
    jndi-name: java:jboss/datasources/pocDS
  jpa:
    database: oracle
    show-sql: false
liquibase:
  enabled: false